menu:
  main:
    - name: "Inicio"
      url: "/"
      weight: 1
    - name: "Alejandro"
      url: "/integrantes/aaf925/"
      weight: 2
    - name: "Antonio"
      url: "/integrantes/anm0200/"
      weight: 3
    - name: "Jorge"
      url: "/integrantes/jgm847/"
      weight: 4
    - name: "Blog"
      url: "/posts/"
      weight: 5