baseURL = "http://localhost:1313/"
title = "M***Hunters"
theme = "PaperMod"

[params]
  defaultTheme = "light"
  disableAutoMenu = true
mainSections = ["posts"]  # Debe coincidir con tu carpeta de contenido

[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Alejandro"
url = "/integrantes/aaf925/"
weight = 2

[[menu.main]]
name = "Antonio"
url = "/integrantes/anm020/"
weight = 3

[[menu.main]]
name = "Jorge"
url = "/integrantes/jgm847/"
weight = 4

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 5

[[menu.main]]
name = "Contacto"
url = "/contacto/"
weight = 6