baseURL = "http://localhost:1313/"
title = "M***Hunters"
theme = "PaperMod"

[params]
defaultTheme = "light"

[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2